version: '3.8'

services:
  blog_frontend:
    build:
      context: ./blog_frontend
    volumes:
      - .:/home/node/blog_frontend
      - /home/node/blog_frontend/node_modules
    ports:
      - "3005:3005"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

